<?xml version="1.0"?>
<robot name="myrobot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPERTY LIST -->
    <xacro:property name="M_PI" value="3.1415926"/>

    <!-- base_link的质量、半径、高度 -->
    <xacro:property name="base_mass"   value="1" />
    <xacro:property name="base_radius"  value="0.1"/>
    <xacro:property name="base_height" value="0.07"/>

    <!-- 万向轮半径、轮子宽度、x轴偏移 -->
    <xacro:property name="caster_mass"    value="0.2" />
    <xacro:property name="caster_radius"  value="0.012"/>
    <xacro:property name="caster_length"    value="0.005" />
    <xacro:property name="caster_joint_x" value="${base_radius-0.02}"/>

    <!-- 运动轮质量、半径、宽度、x轴偏移、z相对于base_link的偏移 -->
    <xacro:property name="wheel_mass"   value="0.2" />
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_length" value="0.025"/>
    <xacro:property name="wheel_joint_x" value="0.0"/>
    <!-- <xacro:property name="wheel_joint_z" value="0.0525"/> -->
    <xacro:property name="wheel_joint_z" value="${caster_radius*2+base_height/2-wheel_radius}"/>


    <!-- Defining the colors used in this robot -->
    <material name="yellow">
        <color rgba="1 0.4 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95"/>
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>

    <!-- Macro for inertia matrix -->
    <xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                iyy="${2*m*r*r/5}" iyz="0"
                izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertial_matrix" params="m l w h">
        <inertial>
             <mass value="${m}" />
             <inertia ixx="${m*(h*h + l*l)/12}" ixy = "0" ixz = "0"
                 iyy="${m*(w*w + l*l)/12}" iyz= "0"
                 izz="${m*(w*w + h*h)/12}" />
        </inertial>
    </xacro:macro>

    <!-- 运动轮的宏 -->
    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="${wheel_joint_x} ${reflect*(base_radius+wheel_length/2)} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
                <material name="gray" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length = "${wheel_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Gray</material>
            <mu1>100000.0</mu1>
            <mu2>100000.0</mu2>
        </gazebo>

        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${prefix}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint" >
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_joint_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- 万向轮定义 -->
    <xacro:macro name="caster" params="prefix reflect">


        <joint name="${prefix}_top_caster_joint" type="continuous">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(base_height/2)}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_top_link"/>
            <axis xyz="0 0 1"/>
        </joint>

        <link name="${prefix}_top_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length = "${caster_length/20}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length = "${caster_length/20}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${caster_mass/20}" r="${caster_radius}" h="${caster_length/20}" />
        </link>

        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="${caster_radius} 0 ${ -caster_radius}" rpy="0 0 0"/>
            <parent link="${prefix}_top_link"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length = "${caster_length}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder radius="${caster_radius}" length = "${caster_length}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${caster_mass}" r="${caster_radius}" h="${caster_length}" />
        </link>

        <gazebo reference="${prefix}_caster_link">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>


    <xacro:macro name="base_gazebo">


        <link name="base_footprint"/>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${base_height/2 + caster_radius*2}" rpy="0 0 0" />
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>

                    <cylinder radius="${base_radius}" length = "${base_height}"/>
                </geometry>
                <material name="yellow" />
            </visual>
            <collision>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${base_radius}" length = "${base_height}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${base_mass}" r="${base_radius}" h="${base_height}" />
        </link>

        <gazebo reference="base_link">
            <material>Gazebo/Yellow</material>
        </gazebo>

        <xacro:wheel prefix="left"  reflect="1"/>
        <xacro:wheel prefix="right" reflect="-1"/>

        <xacro:caster prefix="back"  reflect="-1"/>

        <xacro:caster prefix="front"  reflect="1"/>

        <!-- controller -->
        <gazebo>
            <plugin name="differential_drive_controller"
                    filename="libgazebo_ros_diff_drive.so">
                  <update_rate>30</update_rate>
                  <left_joint>left_wheel_joint</left_joint>
                  <right_joint>right_wheel_joint</right_joint>
                  <wheel_separation>${base_radius*2+wheel_length}</wheel_separation>
                  <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                  <max_wheel_torque>10</max_wheel_torque>
                  <max_wheel_acceleration>1.0</max_wheel_acceleration>
                  <command_topic>cmd_vel</command_topic>
                  <publish_odom>true</publish_odom>
                  <publish_odom_tf>true</publish_odom_tf>
                  <publish_wheel_tf>true</publish_wheel_tf>
                  <odometry_topic>odom</odometry_topic>
                  <odometry_frame>odom</odometry_frame>
                  <robot_base_frame>base_footprint</robot_base_frame>
                  <odometry_source>1</odometry_source>
            </plugin>
        </gazebo>
    </xacro:macro>

</robot>
